[project]
name = "langchain-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kavya", email = "kavya6715257@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "google>=3.0.0",
    "google-genai>=1.47.0",
    "langchain>=0.3.30",
    "python-dotenv>=1.2.1",
]

[project.scripts]
langchain-tutorial = "langchain_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
